# ==============================================================================
# CUSTOM AGENT TOOLS MODULE (tools.py)
# ==============================================================================
# This module contains the tool functions that the Gemini AI Agent can invoke.
# It uses Pydantic to strictly validate the inputs generated by the AI before running
# them. It also manages terminal output formatting (colorized diffs) and prompting 
# the user for approval (Human-in-the-Loop pattern).

import os
import sys
import difflib
import subprocess
import tempfile

# We import Pydantic components:
# - 'BaseModel': a class used to define structured schemas for validation.
# - 'Field': adds descriptions and constraints to schema variables.
# - 'ValidationError': an exception raised when inputs don't match the schema.
from pydantic import BaseModel, Field, ValidationError

# Import our shared state and modular components.
import state
from logger import StructuredLogger
from guardrails import PolicyGuardrail

# Instantiate the structured logger so we can record tool calls and responses.
logger = StructuredLogger()

# ------------------------------------------------------------------------------
# PYDANTIC INPUT SCHEMAS (STRICT SCHEMAS)
# ------------------------------------------------------------------------------

class GetScriptContentInput(BaseModel):
    # This tool takes no arguments, so the schema model is empty.
    pass

class ProposeRefactorInput(BaseModel):
    # 'Field(..., ...)' defines metadata. 
    # '...' (Ellipsis) means this field is REQUIRED.
    # 'min_length' enforces that the AI cannot send an empty string.
    # 'description' is read by the SDK/LLM to understand what this argument does.
    explanation: str = Field(..., min_length=5, description="A clear, educational explanation of the issue and the proposed fix.")
    lesson_summary: str = Field(..., min_length=5, description="A summary of the Bash concepts/rules taught by this change.")
    refactored_code: str = Field(..., min_length=10, description="The complete new content of the script after applying this change.")

class RunShellcheckInput(BaseModel):
    # Takes no arguments.
    pass

class VerifyScriptInput(BaseModel):
    command_to_run: str = Field(..., min_length=1, description="The command to execute (e.g. 'my_func arg1 arg2').")

class SaveChangesInput(BaseModel):
    # Takes no arguments.
    pass

# ------------------------------------------------------------------------------
# TOOL IMPLEMENTATIONS
# ------------------------------------------------------------------------------

def get_script_content() -> str:
    """Returns the current content of the script being refactored.
    
    Always call this tool first to see the script.
    """
    # 1. Log the tool invocation
    logger.log_tool_call("Agent", "get_script_content", {})
    
    # 2. Retrieve code from the shared state object
    content = state.state.content
    
    # 3. Log completion and return the script code
    logger.log_tool_response("Agent", "get_script_content", f"Retrieved {len(content)} characters of code.", outcome="success")
    return content

def propose_refactor(explanation: str, lesson_summary: str, refactored_code: str) -> str:
    """Proposes a single refactoring change to the user.
    
    Args:
        explanation: A clear, educational explanation of the issue and the proposed fix.
        lesson_summary: A summary of the Bash concepts/rules taught by this change.
        refactored_code: The complete new content of the script after applying this change.
    """
    # 1. Log the tool call with incoming arguments
    logger.log_tool_call("RefactorTeacherAgent", "propose_refactor", {
        "explanation": explanation,
        "lesson_summary": lesson_summary,
        "refactored_code": refactored_code
    })

    # 2. STRICT INPUT VALIDATION
    # We attempt to instantiate our ProposeRefactorInput schema. 
    # If the AI sends wrong types or empty values, Pydantic raises a ValidationError.
    try:
        ProposeRefactorInput(
            explanation=explanation,
            lesson_summary=lesson_summary,
            refactored_code=refactored_code
        )
    except ValidationError as e:
        # Catch validation failures, log them, and return a clean error string
        # back to the LLM so it can correct its parameters in the next turn.
        err_msg = f"Strict schema validation failed: {str(e)}"
        logger.log_tool_response("RefactorTeacherAgent", "propose_refactor", err_msg, outcome="validation_error")
        return err_msg

    # 3. RUN LOCAL POLICY GUARDRAILS
    # Verify the code compiles, doesn't contain dangerous operations, and matches scoping rules.
    policy_passed, policy_msg = PolicyGuardrail.validate_code(state.state.content, refactored_code)
    logger.log_policy_check(policy_passed, policy_msg, {
        "explanation": explanation,
        "lesson_summary": lesson_summary
    })
    
    # If policy fails, reject the proposal immediately and tell the AI why
    if not policy_passed:
        err_msg = f"Refactor rejected by local safety guardrail: {policy_msg}"
        logger.log_tool_response("RefactorTeacherAgent", "propose_refactor", err_msg, outcome="guardrail_blocked")
        return err_msg

    # 4. COMPUTE THE DIFF (Code Comparison)
    # Split the original and refactored code into lists of lines
    old_lines = state.state.content.splitlines(keepends=True)
    new_lines = refactored_code.splitlines(keepends=True)
    
    # Compare line-by-line using Python's 'difflib.unified_diff'
    diff_generator = difflib.unified_diff(
        old_lines,
        new_lines,
        fromfile=os.path.basename(state.state.file_path),
        tofile=os.path.basename(state.state.file_path) + " (proposed)"
    )
    diff_text = "".join(diff_generator)
    
    # If the diff is empty, the LLM didn't change anything in the script
    if not diff_text.strip():
        logger.log_tool_response("RefactorTeacherAgent", "propose_refactor", "No diff detected.", outcome="no_diff")
        return "No changes were detected in the proposed refactored_code compared to the current content."
    
    # 5. RENDER THE COLORIZED DIFF AND EXPLANATIONS TO THE USER
    print("\n" + "="*80)
    # \033[1;36m makes the terminal text Bold Cyan. \033[0m resets color.
    print("\033[1;36m[PROPOSED REFACTOR - STEP {}]\033[0m".format(state.state.current_step))
    print(explanation)
    print("-"*80)
    print("\033[1;33m[DIFF]\033[0m") # Bold Yellow
    
    # Loop over the diff text line-by-line and colorize like a git diff
    for line in diff_text.splitlines():
        if line.startswith('+') and not line.startswith('+++'):
            print(f"\033[32m{line}\033[0m") # Green for added lines
        elif line.startswith('-') and not line.startswith('---'):
            print(f"\033[31m{line}\033[0m") # Red for deleted lines
        elif line.startswith('@@'):
            print(f"\033[36m{line}\033[0m") # Cyan for unified diff headers
        else:
            print(line) # Normal formatting
            
    print("-"*80)
    print("\033[1;32m[LESSON SUMMARY]\033[0m") # Bold Green
    print(lesson_summary)
    
    # If the guardrails found warnings (like global variables), display them here
    if "Warning" in policy_msg:
        print("\033[1;31m[POLICY WARNINGS]\033[0m") # Bold Red
        print(policy_msg)
    print("="*80)
    
    # 6. HUMAN-IN-THE-LOOP APPROVAL LOOP
    # We loop indefinitely until the user enters a valid response
    while True:
        try:
            # input() pauses program execution and waits for the user to type something
            # .strip() removes whitespace, .lower() normalizes to lowercase
            choice = input("\nApply this refactor? [y/N]: ").strip().lower()
            if choice in ('y', 'yes'):
                # Save the new code into script memory state
                state.state.content = refactored_code
                state.state.current_step += 1
                logger.log_tool_response("RefactorTeacherAgent", "propose_refactor", "Refactor approved.", outcome="approved")
                return "Refactor applied. Now run shellcheck or verify_script to validate it."
            elif choice in ('n', 'no', ''):
                logger.log_tool_response("RefactorTeacherAgent", "propose_refactor", "Refactor rejected.", outcome="rejected")
                return "Refactor rejected by user. Please propose an alternative or discuss with the user."
            else:
                print("Please enter 'y' or 'n'.")
        except (KeyboardInterrupt, EOFError):
            # If the user hits Ctrl+C (KeyboardInterrupt) or Ctrl+D (EOFError) to exit
            print("\nAborted by user.")
            logger.log_tool_response("RefactorTeacherAgent", "propose_refactor", "Session aborted.", outcome="aborted")
            sys.exit(0)

def run_shellcheck() -> str:
    """Runs shellcheck on the current script content to verify it.
    
    Returns the shellcheck warnings/errors, or a success message if clean.
    """
    logger.log_tool_call("Agent", "run_shellcheck", {})
    
    # Create temporary file to run shellcheck against
    with tempfile.NamedTemporaryFile(mode='w', suffix='.sh', delete=False) as temp_file:
        temp_file.write(state.state.content)
        temp_file_path = temp_file.name
        
    try:
        # Run external process 'shellcheck -s bash <temp_file_path>'
        result = subprocess.run(
            ['shellcheck', '-s', 'bash', temp_file_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        os.unlink(temp_file_path)
        
        # If exit code is 0, shellcheck found no issues
        if result.returncode == 0:
            res_str = "shellcheck passed with no issues."
            logger.log_tool_response("Agent", "run_shellcheck", res_str, outcome="clean")
            return res_str
        elif result.returncode in (-9, 137):
            res_str = "shellcheck execution skipped (restricted by environment sandbox / SIGKILL)."
            logger.log_tool_response("Agent", "run_shellcheck", res_str, outcome="sandbox_restricted")
            return res_str
        else:
            # Replace the temporary filename in the output with the script's actual name
            output = result.stdout.replace(temp_file_path, os.path.basename(state.state.file_path))
            if not output.strip() and result.stderr:
                output = result.stderr.replace(temp_file_path, os.path.basename(state.state.file_path))
            res_str = f"shellcheck found the following issues:\n{output}"
            logger.log_tool_response("Agent", "run_shellcheck", res_str, outcome="issues_found")
            return res_str
            
    except FileNotFoundError:
        # If shellcheck isn't installed in the path
        os.unlink(temp_file_path)
        err_str = "shellcheck command not found. Please install it on the host system."
        logger.log_tool_response("Agent", "run_shellcheck", err_str, outcome="command_not_found")
        return err_str

def verify_script(command_to_run: str) -> str:
    """Runs a test command using the current script state.
    
    This writes the current script content to a temporary file and runs:
    bash -c "source <temp_file> && <command_to_run>"
    
    Args:
        command_to_run: The command to execute (e.g. "my_func arg1 arg2").
    """
    logger.log_tool_call("RefactorTeacherAgent", "verify_script", {"command_to_run": command_to_run})

    # Validate inputs strictly
    try:
        VerifyScriptInput(command_to_run=command_to_run)
    except ValidationError as e:
        err_msg = f"Strict schema validation failed: {str(e)}"
        logger.log_tool_response("RefactorTeacherAgent", "verify_script", err_msg, outcome="validation_error")
        return err_msg

    # Security prompt before running code! (Human-in-the-Loop)
    print("\n" + "="*80)
    print("\033[1;31m[SECURITY NOTICE: EXECUTION REQUEST]\033[0m")
    print(f"The agent wants to run the following test command in Bash:")
    print(f"  source {os.path.basename(state.state.file_path)} && {command_to_run}")
    print("="*80)
    
    while True:
        try:
            choice = input("Allow execution? [y/N]: ").strip().lower()
            if choice in ('y', 'yes'):
                break
            elif choice in ('n', 'no', ''):
                logger.log_tool_response("RefactorTeacherAgent", "verify_script", "Execution denied.", outcome="execution_denied")
                return "Execution denied by user."
            else:
                print("Please enter 'y' or 'n'.")
        except (KeyboardInterrupt, EOFError):
            print("\nAborted.")
            sys.exit(0)
            
    # Write code to temp file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.sh', delete=False) as temp_file:
        temp_file.write(state.state.content)
        temp_file_path = temp_file.name
        
    try:
        # Load functions in the script using 'source' and run the test command
        cmd = f"source {temp_file_path} && {command_to_run}"
        result = subprocess.run(
            ['bash', '-c', cmd],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10 # Stop script after 10 seconds if it hangs
        )
        os.unlink(temp_file_path)
        
        output = []
        if result.stdout:
            output.append(f"--- STDOUT ---\n{result.stdout}")
        if result.stderr:
            output.append(f"--- STDERR ---\n{result.stderr}")
        
        status = f"Exit Code: {result.returncode}"
        output.append(status)
        
        res_str = "\n".join(output)
        
        # Check if subprocess was killed by a sandbox policy
        if result.returncode in (-9, 137):
            res_str = "Execution failed: bash execution was blocked/killed by the environment sandbox (SIGKILL)."
            logger.log_tool_response(
                "RefactorTeacherAgent",
                "verify_script",
                res_str,
                outcome="sandbox_restricted"
            )
            return res_str

        logger.log_tool_response(
            "RefactorTeacherAgent",
            "verify_script",
            res_str,
            outcome="executed_exit_{}".format(result.returncode)
        )
        return res_str
        
    except subprocess.TimeoutExpired:
        os.unlink(temp_file_path)
        err_msg = "Execution timed out after 10 seconds."
        logger.log_tool_response("RefactorTeacherAgent", "verify_script", err_msg, outcome="timeout")
        return err_msg
    except Exception as e:
        if os.path.exists(temp_file_path):
            os.unlink(temp_file_path)
        err_msg = f"Error executing command: {str(e)}"
        logger.log_tool_response("RefactorTeacherAgent", "verify_script", err_msg, outcome="error")
        return err_msg

def save_changes() -> str:
    """Saves the final refactored script back to its original file path.
    
    Call this tool only when the user confirms they are happy with all changes.
    """
    logger.log_tool_call("RefactorTeacherAgent", "save_changes", {})
    try:
        # Open script file in write mode ('w') which overwrites old content
        with open(state.state.file_path, 'w') as f:
            f.write(state.state.content)
        # Set completed flag to stop the main loop
        state.state.completed = True
        res_str = f"Successfully saved all changes to {state.state.file_path}."
        logger.log_tool_response("RefactorTeacherAgent", "save_changes", res_str, outcome="success")
        return res_str
    except Exception as e:
        err_str = f"Failed to save changes to {state.state.file_path}: {str(e)}"
        logger.log_tool_response("RefactorTeacherAgent", "save_changes", err_str, outcome="error")
        return err_str
